# Generated by Django 5.2.4 on 2025-07-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builderapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='layout',
            field=models.CharField(choices=[('column', 'Column'), ('row-image-left', 'Row (Image Left)'), ('row-image-right', 'Row (Image Right)'), ('hover-overlay', 'Hover Overlay')], default='column', max_length=50),
        ),
    ]
